### ISSUE TITLE
Unable to run silq after setting $PATH

### ISSUE THREAD

**Issue by paniash** [eth-sri/silq#10]
I tried installing silq from source and it installed just fine. I'm able to run using `./silq` when I'm in the corresponding directory. However, I'm facing an issue when addin silq to my `$PATH`. I did it the way as suggested on the website. 

Now when I'm running silq from any directory, I get the following error: (I'm running zsh)
```
zsh: permission denied: silq
```
When I switch over to bash, I get the error:
```
bash: silq: command not found
```

**Comment by tgehr** [comment]
Given that you get permission denied, the most likely explanation is that your symbolic link is currently pointing to the silq directory instead of the silq binary.
Go to the directory with the silq binary and run:
```
.../silq$ sudo rm /usr/local/bin/silq
.../silq$ sudo ln -s $(pwd)/silq /usr/local/bin/silq
```
Let me know if that fixes your issue.

**Comment by paniash** [comment]
Yeah, sorry I had the symbolic link pointing to the directory and not the binary. It now works as expected! Thanks a lot @tgehr!

**Comment by ZoeDreams** [comment]
should have a silq doctor command that checks these sorts of things.
