### ISSUE TITLE
Small error in the documentation?

### ISSUE THREAD

**Issue by programizer** [eth-sri/silq#14]
[Here](https://silq.ethz.ch/documentation#/documentation/7_symbols) in the Unicode table it says to type out 𝔹 for 𝔹 which isn't much help. I think, it should say \bb because that works.

**Comment by programizer** [comment]
Also
\BbbN -> \Bbb{N}
\BbbR -> \Bbb{R}
btw, which is probably because freebroccolo.input-assist has been updated since the documentaion was written.
But the first comment isn't just an issue of an old version.

**Comment by tgehr** [comment]
Thanks for reporting! \bb, \bn, \br, ... work. I'll close this after the documentation has been fixed.
