### ISSUE TITLE
Cann't run silq in vscode

### ISSUE THREAD

**Issue by usj-django-dev** [eth-sri/silq#15]
I already installed the two packages that is necessary and add silq in json file but every time i run silq code it says that code language is not supported or defined. plz, Se those picture

![pack](https://user-images.githubusercontent.com/69731170/90676457-daed5e00-e27d-11ea-920f-71c82a724bdc.PNG)
![json](https://user-images.githubusercontent.com/69731170/90676483-e6d92000-e27d-11ea-9fd0-bee8f8a84c4a.PNG)

**Comment by bichselb** [comment]
Could you provide the full error message your are getting, and where this error appears?

The following could also help:
- the name of the file you are trying to run
- the content of the file you are trying to run
- the steps you take to run this file
- the error message, as it appears from vscode

**Comment by tgehr** [comment]
Treating as resolved, please reopen if that is not the case.

**Comment by usj-django-dev** [comment]
I stopped learning silq.
