### ISSUE TITLE
Module imports

### ISSUE THREAD

**Issue by j6k4m8** [eth-sri/silq#18]
Hi team! 

I'm curious if there has been any discussion about code packaging or library design, or, more generally, file imports:

```D
import foo from "foo.slq"

def main() {
    return foo(...)
}
```

Right now, I run a simple script that replaces "`import X`" in my files with the contents of file `X` in that directory. Hacky, but helps with organization, and centralizing commonly-used util functions. But of course this is a poor substitute for real imports, and means that there's no good type-checking until runtime!

**Comment by tgehr** [comment]
`import foo;` already imports `foo.slq` from the directory where silq was invoked from, you can import from subdirectories using `import directory.file`. One thing that's been on my TODO list is relative imports, similar to how Python does it (c.f. https://realpython.com/absolute-vs-relative-python-imports/) and symbol renaming to avoid clashes.

**Comment by j6k4m8** [comment]
Ah, thank you for the pointer!
Interesting. Encountered a "`foo.slq: no such file`" error when I tried this in VSCode (all in the top-level directory of my project). Closed VSCode, came back, reopened it, and works like a charm. I'm guessing this is my error — thanks!!
