### ISSUE TITLE
Constructing an array of parametrized length

### ISSUE THREAD

**Issue by j6k4m8** [eth-sri/silq#19]
Excited to share what I suspect is my silly mistake with you :)

> ### Background
> I want to compute the function <img src="https://render.githubusercontent.com/render/math?math=x_0\oplus(x_1 \times x_2 \times ... \times x_n)">; 
> 
> in other words, `x0 XOR (x1 AND x2 AND ... AND xn)`
>
> My approach to do this is to first construct an array of length n-1, and then use [something like this function](https://github.com/eth-sri/silq/pull/8#issuecomment-657742646) to construct the `all` of that array.

### My challenge: 
I am trying to construct an array inside a parametrized function, like so:

```C
def x1_xor_xn[n: !ℕ](input: uint[n]) {
    
    xn := 0:𝔹^(n-1);

    ...
}
```

But it doesn't seem I can construct new primitives with my parameter `n` even though I define it to be of classical-ℕ type:

```C
❌ vector length should be of type !ℕ, not !ℤ
```

Likewise, constructing an int array fails:

```C
xn := 0:uint[n-1]; // ❌ expected argument types !ℕ, but !ℤ was provided
```

And so does this silliness:

```C
xn := 0:𝔹^((n-(1 as !ℕ)) as !ℕ);
// or:
xn := 0:uint[max(1, n-1) as !ℕ];
```

It appears that `1` is interpreted as `!ℤ` and nothing I do can convince the compiler that I actually mean `!ℕ`, perhaps because ℕ-ℕ→ℤ...

**What is the correct way to construct something like this? Is this possible in silq right now? (Is there some magical way to parametrize the `n` type?)**

**Comment by tgehr** [comment]
You can use `n-1 coerce !ℕ` or `n sub 1`. Both will check at runtime that the result indeed fits into `!ℕ`.
But I think what you want is just this:
```
def x1_xor_xn[n:!ℕ](x: 𝔹^n)lifted ⇒ x[0]⊕all(x[1..n]);
```

**Comment by j6k4m8** [comment]
Aha!! It was that indexing notation precisely that I was looking for, too!
I was trying all sorts of numpy flavored things like x[1:] etc. this is
perfect, thank you!!

**Comment by j6k4m8** [comment]
@tgehr I also learned about "fat-arrow" ⇒ function notation from your comment! Super helpful, thanks!
