### ISSUE TITLE
Error message when I execute this comando ./ dependencies-release and build-release

### ISSUE THREAD

**Issue by marcosleandro9205** [eth-sri/silq#2]
After running ./dependencies-release.sh , I have this message , why?
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git

After running ./build-release.sh , I have this message , why?
Error: module * is in file 'ast/*.d' which cannot be read
import path[0] = /home/user/Downloads/silq-master/ldc2-1.18.0-linux-x86_64/bin/../import

**Comment by tgehr** [comment]
I assume you downloaded a zip file instead of cloning with git. Either use git clone or manually download the submodules too. (https://github.com/tgehr/ast and https://github.com/tgehr/util)

**Comment by tgehr** [comment]
Also see: https://silq.ethz.ch/install
