### ISSUE TITLE
Function calls omitting variables in square brackets causes errors when reversing

### ISSUE THREAD

**Issue by marco-lewis** [eth-sri/silq#26]
Variables in square brackets can be omitted in function calls if they can be derived from variables in the operation. For example:

```
def op[n:!N](q:uint[n], anc:B){
  for i in [0..n){
    anc xorb=q[i];
  }
}

n:=5;

def main(){
  q := 0:uint[n];
  anc := op(q, 0:B);
  ...
}
```

When reversing, omitting the square brackets causes an error:
```
def main(){
  q := 0:uint[n];
  (q, anc) := op(q, 0:B);
  (q, 0:B) := reverse(op)(q, anc); // Error
  return q;
}
```

A current workaround is to include the square brackets within the reverse call ```reverse(op[n])(...)```, but perhaps there is a way to avoid this.

(I am currently using the vscode extension for Silq but not sure if this error occurs in other builds.)

**Comment by tgehr** [comment]
Thanks for reporting! I agree that this should just work.

**Comment by tgehr** [comment]
Implemented in https://github.com/eth-sri/silq/commit/6530720a3388a87eb22c7edcd6646c3f82f51566. Works with vscode plugin 0.0.35.

Besides `(q, 0:𝔹) := reverse(op)(q, anc)`, it is now also possible to do `op(q, 0:𝔹) := (q, anc)`.
This works by rewriting `reverse(op)` to `[n:!ℕ]⇒reverse(op[n])` under the hood. This means it is a first-class value, e.g.:

```silq
rop := reverse(op);
(q, 0:𝔹) := rop(q, anc);
```

(Here, `rop` works with any number of bits, just like `op` did.)
