### ISSUE TITLE
Variable quantum state assignment

### ISSUE THREAD

**Issue by timo-cmd2** [eth-sri/silq#31]
Hey again 👋🏻

Just wanted to ask, how Silq manages to handle Variables. As far as I know, quantum states cannot be stored inside a variable since the measurement will trigger a mirror-state.

Best regards
Timo Sarkar

Zug, Switzerland

**Comment by tgehr** [comment]
Hi Timo,

An assignment

```Silq
x=f(x,y)
```

is treated like:

```Silq
x'=x;
x:=f(x',y);
forget(x');
```

`forget(x')` is only valid if the type checker can show that it is possible to synthesize an expression `g(x,y)` such that `forget(x'=g(x,y))` would work. To run the code on a quantum computer, this code synthesis has to be performed during compilation. (This is relatively straightforward for the cases that Silq currently allows.)

Best,
Timon

**Comment by timo-cmd2** [comment]
Allright thanks !!
