### ISSUE TITLE
Please elaborate the process to install silq in any arch linux derivative(specifically needed for blackarch linux).

### ISSUE THREAD

**Issue by SK-099** [eth-sri/silq#34]
I am unable to install silq in my Blackarch Linux OS. I want to install it in terminal since I don't use any IDE's. I code in vim through terminal and then compile or interpret it with respective compiler or interpreter of the concerned language. Here, I want to do the same. Please tell me the steps to install in it my terminal and run it through commands as I request.

**Comment by tgehr** [comment]
What is precisely your issue? Which step of the instructions is failing and with what error message?

**Comment by tgehr** [comment]
Closing this issue now as it is unclear and inactive, feel free to reopen if you want to provide further details.
